name: CD Compute

on:
  push:
    branches:
      - 'preprod'
      - 'prod'

  workflow_dispatch:

jobs:
  deploy-app:
    if: ${{ github.ref_name == 'prod' || github.ref_name == 'preprod' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_REGION: eu-west-3
    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - run: sam build

      - name: Deploy app
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ github.ref_name }}-compute-jcloudify-billing-retriever --capabilities CAPABILITY_NAMED_IAM --parameter-overrides Env=${{ github.ref_name }} --resolve-s3 --tags app=jcloudify-billing-retriever env=${{ github.ref_name }}